steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
    dir: "src/frontend"

  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
    dir: "src/frontend"

  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      ["-c", "docker pull gcr.io/$PROJECT_ID/expunge-service:base || exit 0"]

  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      ["-c", "docker pull gcr.io/$PROJECT_ID/expunge-service:build || exit 0"]

  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      ["-c", "docker pull gcr.io/$PROJECT_ID/expunge-service:prod || exit 0"]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/expunge-service:base",
        "--target",
        "base",
        "--cache-from",
        "gcr.io/$PROJECT_ID/expunge-service:base",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/expunge-service:build",
        "--target",
        "build",
        "--cache-from",
        "gcr.io/$PROJECT_ID/expunge-service:base",
        "--cache-from",
        "gcr.io/$PROJECT_ID/expunge-service:build",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/expunge-service:prod",
        "--cache-from",
        "gcr.io/$PROJECT_ID/expunge-service:base",
        "--cache-from",
        "gcr.io/$PROJECT_ID/expunge-service:build",
        "--cache-from",
        "gcr.io/$PROJECT_ID/expunge-service:prod",
        ".",
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/expunge-service:prod']

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "eviction-sponge",
        "--image",
        "gcr.io/$PROJECT_ID/expunge-service:prod",
        "--region",
        "us-west1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

images:
  [
    "gcr.io/$PROJECT_ID/expunge-service:base",
    "gcr.io/$PROJECT_ID/expunge-service:build",
    "gcr.io/$PROJECT_ID/expunge-service:prod",
  ]

timeout: 1500s
